In [1]:
# import numpy 
import numpy as np 

In [2]:
# 1D array of length 3 with all values 0 
Z1 = np.zeros(3)
print(Z1)

[0. 0. 0.]


In [3]:
# 2D array of 3x4 with all values 0 
Z2 = np.zeros((3,4))
print(Z2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [4]:
# 1D array of length 3 with all values 1
A1 = np.ones(3)  
print(A1) 

[1. 1. 1.]


In [5]:
# 2D array of 3x4 with all values 1
A2 = np.ones((3,4))
A2
print(A2) 

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [6]:
# not specify start and step 
A1 = np.arange(10)
print(A1)

[0 1 2 3 4 5 6 7 8 9]


In [7]:
# specifying start and step 
A2 = np.arange(start=1, stop=10, step=2)
print(A2)

[1 3 5 7 9]


In [8]:
# another way 
A3 = np.arange(10, 25, 2)
print(A3)

[10 12 14 16 18 20 22 24]


In [9]:
# array of evenly spaced values 0 to 2, here sample size = 9
L1 = np.linspace(0,2,9)
print(L1)

[0.   0.25 0.5  0.75 1.   1.25 1.5  1.75 2.  ]


In [10]:
# Array of 6 evenly divided values from 0 to 100
L2 = np.linspace(0, 100, 6)
print(L2) 

[  0.  20.  40.  60.  80. 100.]


In [11]:
# Array of 1 to 5
L3 = np.linspace(start=1, stop=5, endpoint=True, retstep=False)
print(L3) 

[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


In [12]:
# Array of 1 to 5
L4 = np.linspace(start=1, stop=5, endpoint=True, retstep=True)
print(L4) 

(array([1.        , 1.08163265, 1.16326531, 1.24489796, 1.32653061,
       1.40816327, 1.48979592, 1.57142857, 1.65306122, 1.73469388,
       1.81632653, 1.89795918, 1.97959184, 2.06122449, 2.14285714,
       2.2244898 , 2.30612245, 2.3877551 , 2.46938776, 2.55102041,
       2.63265306, 2.71428571, 2.79591837, 2.87755102, 2.95918367,
       3.04081633, 3.12244898, 3.20408163, 3.28571429, 3.36734694,
       3.44897959, 3.53061224, 3.6122449 , 3.69387755, 3.7755102 ,
       3.85714286, 3.93877551, 4.02040816, 4.10204082, 4.18367347,
       4.26530612, 4.34693878, 4.42857143, 4.51020408, 4.59183673,
       4.67346939, 4.75510204, 4.83673469, 4.91836735, 5.        ]), 0.08163265306122448)


In [13]:
# generate an array with 5 samples with base 10.0 
np.logspace(1, 10, num=5, endpoint=True)

array([1.00000000e+01, 1.77827941e+03, 3.16227766e+05, 5.62341325e+07,
       1.00000000e+10])

In [14]:
# generate an array with 5 samples with base 2.0
np.logspace(1, 10, num=5, endpoint=True, base=2.0)

array([   2.        ,    9.51365692,   45.254834  ,  215.2694823 ,
       1024.        ])

In [15]:
# generate 2x2 constant array, constant = 7
C = np.full((2, 2), 7)
print(C)

[[7 7]
 [7 7]]


In [16]:
# generate 2x2 identity matrix 
I = np.eye(2)
print(I) 

[[1. 0.]
 [0. 1.]]


In [17]:
# create an array with randomly generated 5 values 
R = np.random.rand(5)
print(R)

[0.34308705 0.19354136 0.33938215 0.79526383 0.58777441]


In [18]:
# generate 2x2 array of random values 
R1 = np.random.random((2, 2))
print(R1)

[[0.30802742 0.31398097]
 [0.1931638  0.29477264]]


In [19]:
# generate 4x5 array of random floats between 0-1
R2 = np.random.rand(4,5)
print(R2)

[[0.67958171 0.64419173 0.25179614 0.8639893  0.01368429]
 [0.00501327 0.4061684  0.53401233 0.29845628 0.91684883]
 [0.11560919 0.11848508 0.57141627 0.05462069 0.96218206]
 [0.47041845 0.0317144  0.91851588 0.05734863 0.56567389]]


In [20]:
# generate 6x7 array of random floats between 0-100
R3 = np.random.rand(6,7)*100
print(R3)

[[ 0.40743471 79.91769624  9.78477716 81.28666666 78.47255078 65.21381486
  11.18188058]
 [48.04687316 21.96698278 95.98245479 26.43875402 35.44447316 63.95145226
  46.36434028]
 [81.29788056 95.0789305  47.40738044  9.06278534 39.91452877 52.50139568
  64.69903768]
 [45.57635164 22.25654514 74.13982822 23.90399245 27.97782988  2.79345016
  97.66761419]
 [ 7.10643359 73.21097093 31.56224178 28.02797827 73.15935656 39.15908519
  10.19918936]
 [ 6.32980799 99.21599102 93.33525747 55.91349151 25.24411391 20.03250819
  57.06063079]]


In [21]:
# generate 2x3 array of random ints between 0-4
R4 = np.random.randint(5, size=(2,3))
print(R4)

[[4 2 3]
 [1 4 0]]


In [22]:
# generate an empty array 
E1 = np.empty(2) 
print(E1)

[9.9e-324 1.5e-323]


In [23]:
# 2x2 empty array
E2 = np.empty((2, 2)) 
print(E2)

[[0.30802742 0.31398097]
 [0.1931638  0.29477264]]


In [24]:
# generate an array of floats 
D = np.ones((2, 3, 4), dtype=np.float16)
D

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]], dtype=float16)