In [1]:
# import numpy 
import numpy as np

In [2]:
# create an array `A1`
A1 = np.arange(10)
print(A1)

[0 1 2 3 4 5 6 7 8 9]


In [3]:
# copy `A1` into A2 
A2 = np.copy(A1)
print(A2)

[0 1 2 3 4 5 6 7 8 9]


In [4]:
# view of array A2 
A3 = A2.view(np.float16)
print(A3)

[0.0e+00 0.0e+00 0.0e+00 0.0e+00 6.0e-08 0.0e+00 0.0e+00 0.0e+00 1.2e-07
 0.0e+00 0.0e+00 0.0e+00 1.8e-07 0.0e+00 0.0e+00 0.0e+00 2.4e-07 0.0e+00
 0.0e+00 0.0e+00 3.0e-07 0.0e+00 0.0e+00 0.0e+00 3.6e-07 0.0e+00 0.0e+00
 0.0e+00 4.2e-07 0.0e+00 0.0e+00 0.0e+00 4.8e-07 0.0e+00 0.0e+00 0.0e+00
 5.4e-07 0.0e+00 0.0e+00 0.0e+00]


In [5]:
# Unsorted array
A4 = np.array([9, 2, 3,1, 5, 10])
print(A4) 

[ 9  2  3  1  5 10]


In [6]:
# Call sort function
A4.sort()
print(A4)

[ 1  2  3  5  9 10]


In [7]:
# Row and column unsorted
A5 = np.array([[4, 1, 3], [9, 5, 8]])
print(A5) 

[[4 1 3]
 [9 5 8]]


In [8]:
# Apply sort function on column axis=1
A5.sort(axis=1)
print(A5)

[[1 3 4]
 [5 8 9]]


In [9]:
# 2D array
A6 = np.array([[4, 1, 3], [9, 5, 8]])
# 1D array 
A6.flatten()

array([4, 1, 3, 9, 5, 8])

In [10]:
A7 = np.array([[4, 1, 3], [9, 5, 8]])
A7

array([[4, 1, 3],
       [9, 5, 8]])

In [11]:
# Transpose A7 
A7.T

array([[4, 9],
       [1, 5],
       [3, 8]])

In [12]:
A8 = np.array([(8,9,10),(11,12,13)])
A8

array([[ 8,  9, 10],
       [11, 12, 13]])

In [13]:
# Reshape --> 3x4
A8.reshape(3,2)

array([[ 8,  9],
       [10, 11],
       [12, 13]])

In [14]:
A9 = np.array([(8,9,10),(11,12,13)])
A9

array([[ 8,  9, 10],
       [11, 12, 13]])

In [15]:
# Resize 
A9.resize(3, 2)
A9

array([[ 8,  9],
       [10, 11],
       [12, 13]])