In [1]:
# add 2 lists 
L1 = [1, 2, 3]
L2 = [4, 5, 6]
print(L1+L2)

[1, 2, 3, 4, 5, 6]


In [2]:
# element wise sum using numpy array 
import numpy as np 
A1 = np.array([1, 2, 3])
A2 = np.array([4, 5, 6])
print(A1+A2)

[5 7 9]


In [3]:
import numpy as np
import time
import sys
S = range(1000)
print("Python List: ", sys.getsizeof(5)*len(S))
 
D = np.arange(1000)
print("Numpy Array: ", D.size*D.itemsize)

Python List:  28000
Numpy Array:  8000


In [4]:
import time
import sys
 
SIZE = 1000000
 
L1 = range(SIZE)
L2 = range(SIZE)
A1 = np.arange(SIZE)
A2 = np.arange(SIZE)
 
start= time.time()
result=[(x,y) for x,y in zip(L1,L2)]
# time in ms 
print((time.time()-start)*1000)
 
start = time.time()
result = A1+A2
# time in ms 
print((time.time()-start)*1000)

217.01884269714355
49.56817626953125


In [5]:
%timeit sum(range(1000))

15.1 µs ± 114 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [6]:
%timeit np.sum(np.arange(1000))

7.61 µs ± 58.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [7]:
# import numpy 
import numpy as np 

In [8]:
# Creating 1D array
A = np.array([1, 2, 3])
print(A)

[1 2 3]


In [9]:
# type 
print(type(A))

<class 'numpy.ndarray'>


In [10]:
# create an array with categorical entities. 
X = np.array([12, 13, "n"])
print(X)

['12' '13' 'n']


In [11]:
# type 
print(type(X))

<class 'numpy.ndarray'>


In [12]:
# Creating 2D array
A2 = np.array([[3, 4, 5], [7, 8, 9]])
print(A2) 

[[3 4 5]
 [7 8 9]]


In [13]:
# Creating 3D array
A3 = np.array([[(1, 2, 3), (4, 5, 6)], [(7, 8, 9), (10, 11, 12)]])
print(A3) 

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [14]:
A1 = np.array([1, 2, 3,4, 5])
# size 
A1.size

5

In [15]:
A2 = np.array([[4, 5, 6], [7, 8, 9]])
# shape 
A2.shape 

(2, 3)

In [16]:
# get row 
A2.shape[0]

2

In [17]:
# get column
A2.shape[1]

3

In [18]:
A3 = np.linspace(0, 100, 6)
# dtypes 
A3.dtype

dtype('float64')

In [19]:
A4 = np.ones((2,3))
# convert 
A4.astype(np.float16)

array([[1., 1., 1.],
       [1., 1., 1.]], dtype=float16)

In [20]:
A5 = np.linspace(0, 100, 20)
# array to list 
A5.tolist() 

[0.0,
 5.2631578947368425,
 10.526315789473685,
 15.789473684210527,
 21.05263157894737,
 26.315789473684212,
 31.578947368421055,
 36.8421052631579,
 42.10526315789474,
 47.36842105263158,
 52.631578947368425,
 57.89473684210527,
 63.15789473684211,
 68.42105263157896,
 73.6842105263158,
 78.94736842105263,
 84.21052631578948,
 89.47368421052633,
 94.73684210526316,
 100.0]

In [21]:
np.info(np.linspace)

 linspace(*args, **kwargs)

Return evenly spaced numbers over a specified interval.

Returns `num` evenly spaced samples, calculated over the
interval [`start`, `stop`].

The endpoint of the interval can optionally be excluded.

.. versionchanged:: 1.16.0
    Non-scalar `start` and `stop` are now supported.

Parameters
----------
start : array_like
    The starting value of the sequence.
stop : array_like
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.
num : int, optional
    Number of samples to generate. Default is 50. Must be non-negative.
endpoint : bool, optional
    If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
retstep : bool, optional
    If True, return (`samples`, `step`), where `step` is the spacing
    between samples.
dty